# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['d:\\trae_projects\\Stock_strategies\\StockStrategy_1020'],
    binaries=[],
    datas=[
        ('assets\\styles.css', 'assets'),
        ('A股上市公司名单\\A股上市公司名单.csv', 'A股上市公司名单'),
    ],
    hiddenimports=[
        'dash',
        'dash.dcc',
        'dash.html',
        'dash.dependencies',
        'plotly',
        'plotly.graph_objects',
        'pandas',
        'numpy',
        'tushare',
        'config',
        'config.settings',
        'config.tushare_token',
        'models',
        'models.signal',
        'models.stock',
        'services',
        'services.data_service',
        'services.strategy_service',
        'services.chart_service',
        'services.signal_scanner',
        'services.data_updater',
        'views',
        'views.app_view',
        'utils',
        'utils.logger',
        'utils.path_helper',
        'utils.helpers',
        'constants',
        'core',
        'core.backtest_engine',
        'core.data_validator',
        'strategies',
        'strategies.base_strategy',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)